
path:
  data: /data/data
  logs: /data/log
  plugins: /opt/logstash/plugins
  work: /data/work

cluster:
  name: ${ES_CLUSTER_NAME}

cloud:
  aws:
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    region: ${ES_AWS_REGION}

discovery:
  type: ec2
  ec2:
    tag:
      cluster: ${ES_CLUSTER_NAME}
  zen:
    ping:
      multicast:
        enabled: false

network:
  publish_host: _ec2:privateIp_

node.master: false
node.data: false
plugin.mandatory: cloud-aws

indices.fielddata.cache.size: 15%
